export enum FinancialStatement {
  BALANCE_SHEET = 'BALANCE_SHEET',
  INCOME_STATEMENT = 'INCOME_STATEMENT',
  CASH_FLOW_STATEMENT = 'CASH_FLOW_STATEMENT',
  CHANGES_IN_EQUITY = 'CHANGES_IN_EQUITY',
}

